# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:32:56+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import (
    APIKeyHeader,
    BaseSecurity,
    UnsuportedSecurityStub,
)
from fastapi import Path

from models import (
    CollectionResponsePublicBusinessUnitNoPaging,
    Error,
    Name,
    Properties,
)

app = MCPProxy(
    description='Retrieve Business Unit information.',
    title='Business Unit',
    version='v3',
    servers=[{'url': 'https://api.hubapi.com/'}],
)


@app.get(
    '/business-units/v3/business-units/user/{userId}',
    description=""" Get Business Units identified by `userId`. The `userId` refers to the user’s ID. """,
    tags=['business_unit_management'],
    security=[
        APIKeyHeader(name="private-app-legacy"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def get__business_units_v3_business_units_user__user_id_(
    user_id: str = Path(..., alias='userId'),
    properties: Optional[Properties] = None,
    name: Optional[Name] = None,
):
    """
    Get Business Units for a user
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
