# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:32:56+00:00

from __future__ import annotations

from typing import Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class ErrorDetail(BaseModel):
    code: Optional[str] = Field(
        None, description='The status code associated with the error detail'
    )
    context: Optional[Dict[str, List[str]]] = Field(
        None,
        description='Context about the error condition',
        examples=[{'missingScopes': ['scope1', 'scope2']}],
    )
    in_: Optional[str] = Field(
        None,
        alias='in',
        description='The name of the field or parameter in which the error was found.',
    )
    message: str = Field(
        ...,
        description='A human readable message describing the error along with remediation steps where appropriate',
    )
    subCategory: Optional[str] = Field(
        None,
        description='A specific category that contains more specific detail about the error',
    )


class PublicBusinessUnitLogoMetadata(BaseModel):
    logoAltText: Optional[str] = Field(None, description="The logo's alt text")
    logoUrl: Optional[str] = Field(None, description="The logo's url")
    resizedUrl: Optional[str] = Field(None, description="The logo's resized url")


class Properties(RootModel[List[str]]):
    root: List[str]


class Name(RootModel[List[str]]):
    root: List[str]


class Error(BaseModel):
    category: str = Field(..., description='The error category')
    context: Optional[Dict[str, List[str]]] = Field(
        None,
        description='Context about the error condition',
        examples=[
            {
                'invalidPropertyName': ['propertyValue'],
                'missingScopes': ['scope1', 'scope2'],
            }
        ],
    )
    correlationId: UUID = Field(
        ...,
        description='A unique identifier for the request. Include this value with any error reports or support tickets',
        examples=['aeb5f871-7f07-4993-9211-075dc63e7cbf'],
    )
    errors: Optional[List[ErrorDetail]] = Field(
        None, description='further information about the error'
    )
    links: Optional[Dict[str, str]] = Field(
        None,
        description='A map of link names to associated URIs containing documentation about the error or recommended remediation steps',
    )
    message: str = Field(
        ...,
        description='A human readable message describing the error along with remediation steps where appropriate',
        examples=['An error occurred'],
    )
    subCategory: Optional[str] = Field(
        None,
        description='A specific category that contains more specific detail about the error',
    )


class PublicBusinessUnit(BaseModel):
    id: str = Field(..., description="The Business Unit's unique ID")
    logoMetadata: Optional[PublicBusinessUnitLogoMetadata] = None
    name: str = Field(..., description="The Business Unit's name")


class CollectionResponsePublicBusinessUnitNoPaging(BaseModel):
    results: List[PublicBusinessUnit] = Field(
        ..., description='The collection of Business Units'
    )
